name: context example

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show info
        run: echo runs on ${{ runner.environment }} and name of the job is ${{ runner.name }} 
