name: example

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get repo
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello Patrick

      - name: Run a multi-line script
        run: | 
          echo Hello Patrick
          echo Second Hello Patrick        

      - name: show Readme.md file
        run: cat README.md
      