name: variable and secret usage

on: push
env:
  WORKFLOW_LEVEL: workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL: Job 
  
    steps:
      - name: show variables1
        env:
          STEP_LEVEL: step
        run: echo $WORKFLOW_LEVEL and ${{ env.JOB_LEVEL }} and $STEP_LEVEL again

        
   
      - name: show variables2
        env:
          STEP_LEVEL: step
        run: | 
          echo $WORKFLOW_LEVEL
          echo ${{ env.JOB_LEVEL}} 
          echo $STEP_LEVEL

      - name: show the vars from github vars
      run: echo "show the variable defined at repository level in github:" ${{ vars.USERNAME_PATRICK }} 
          
      - name: show the secret from github secrets
        run: echo "show the secret defined at repository level in github:" ${{ secrets.PASSWORD_PATRICK }}