name: run manually action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: echo something
        run: echo because of the workflow_dispatch setting this can be run manually
